import type { Vehicle } from './types';

export const VEHICLE_DATABASE: Vehicle[] = [
  // Existing Cars
  {
    id: 'ford-falcon-fg-turbo',
    make: 'Ford',
    model: 'Falcon',
    variant: 'FG/FG-X Turbo (Barra)',
    years: '2008-2016',
    imageId: 'ford-falcon-fg-turbo',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Automatic Transmission Fluid (ZF 6HP)', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid (TR-6060)', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 150000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
  },
  {
    id: 'toyota-86',
    make: 'Toyota',
    model: '86 / GR86',
    variant: 'GT / GTS / ZN6 / ZN8',
    years: '2012-Present',
    imageId: 'toyota-86',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 9, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 105000, oemIntervalMonths: 84, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant (Super Long Life)', oemIntervalKm: 160000, oemIntervalMonths: 96, type: 'Chassis' },
    ],
  },
  {
    id: 'sv6-commodore',
    make: 'Holden',
    model: 'Commodore',
    variant: 'SV6 (VE/VF - V6)',
    years: '2006-2017',
    imageId: 'sv6-commodore',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 9, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 120000, oemIntervalMonths: 84, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 240000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
  },
  // New Cars
  // Nissan Skylines
  {
    id: 'nissan-skyline-r32-gtst',
    make: 'Nissan',
    model: 'Skyline',
    variant: 'R32 GTS-t (RB20DET)',
    years: '1989-1994',
    imageId: 'placeholder-coupe-gray',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 5000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 20000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
  },
  {
    id: 'nissan-skyline-r32-gtr',
    make: 'Nissan',
    model: 'Skyline GT-R',
    variant: 'R32 (RB26DETT)',
    years: '1989-1994',
    imageId: 'placeholder-coupe-dark',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 5000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Platinum)', oemIntervalKm: 20000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis', transmission: 'Manual' },
      { name: 'Front Differential Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Rear Differential Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'ATTESA Transfer Case Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
  },
  {
    id: 'nissan-skyline-r33-gtst',
    make: 'Nissan',
    model: 'Skyline',
    variant: 'R33 GTS25t (RB25DET)',
    years: '1993-1998',
    imageId: 'placeholder-coupe-blue',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 7500, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Platinum)', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
  },
  {
    id: 'nissan-skyline-r34-gtt',
    make: 'Nissan',
    model: 'Skyline',
    variant: 'R34 GTT (RB25DET NEO)',
    years: '1998-2002',
    imageId: 'placeholder-coupe-silver',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Platinum)', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
  },
  {
    id: 'nissan-skyline-r34-gtr',
    make: 'Nissan',
    model: 'Skyline GT-R',
    variant: 'R34 (RB26DETT)',
    years: '1999-2002',
    imageId: 'placeholder-coupe-blue-fast',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 7500, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid (Getrag)', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Front Differential Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Rear Differential Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'ATTESA Transfer Case Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
  },
  // Ford Falcons
  {
    id: 'ford-falcon-au',
    make: 'Ford',
    model: 'Falcon',
    variant: 'AU I6 (Intech)',
    years: '1998-2002',
    imageId: 'placeholder-sedan-gold',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 45000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 150000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
  },
  {
    id: 'ford-falcon-ba-bf',
    make: 'Ford',
    model: 'Falcon',
    variant: 'BA/BF I6 (Barra)',
    years: '2002-2008',
    imageId: 'placeholder-sedan-silver',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Automatic Transmission Fluid (4-speed)', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 45000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 240000, oemIntervalMonths: 120, type: 'Chassis' },
    ],
  },
  // VW Golf R
  {
    id: 'vw-golf-r-mk5',
    make: 'Volkswagen',
    model: 'Golf R32',
    variant: 'Mk5 (3.2 VR6)',
    years: '2005-2008',
    imageId: 'placeholder-hatch-blue',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Haldex Fluid & Filter', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'DSG Transmission Fluid & Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Manual' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 150000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
  },
  {
    id: 'vw-golf-r-mk6',
    make: 'Volkswagen',
    model: 'Golf R',
    variant: 'Mk6 (EA113)',
    years: '2009-2013',
    imageId: 'placeholder-hatch-black',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt & Water Pump', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Cam Follower', oemIntervalKm: 20000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Haldex Fluid & Filter', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'DSG Transmission Fluid & Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Manual' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
  },
  {
    id: 'vw-golf-r-mk7',
    make: 'Volkswagen',
    model: 'Golf R',
    variant: 'Mk7/7.5 (EA888 Gen3)',
    years: '2013-2020',
    imageId: 'placeholder-hatch-lapiz',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Haldex Fluid', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'DSG Transmission Fluid & Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 120000, oemIntervalMonths: 96, type: 'Chassis', transmission: 'Manual' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
  },
  {
    id: 'vw-golf-r-mk8',
    make: 'Volkswagen',
    model: 'Golf R',
    variant: 'Mk8 (EA888 Gen4)',
    years: '2021-Present',
    imageId: 'placeholder-hatch-white-modern',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Haldex Fluid', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'DSG Transmission Fluid & Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
  },
  // Other Cars
  {
    id: 'mercedes-ml500',
    make: 'Mercedes-Benz',
    model: 'ML 500',
    variant: 'W164 (M273 V8)',
    years: '2007-2011',
    imageId: 'placeholder-suv-black',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 20000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Automatic Transmission Fluid (7G-Tronic)', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Transfer Case Fluid', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis' },
      { name: 'Front Differential Fluid', oemIntervalKm: 120000, oemIntervalMonths: 72, type: 'Chassis' },
      { name: 'Rear Differential Fluid', oemIntervalKm: 120000, oemIntervalMonths: 72, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
  },
  {
    id: 'ford-mondeo-mc',
    make: 'Ford',
    model: 'Mondeo',
    variant: 'MC EcoBoost',
    years: '2015-2022',
    imageId: 'placeholder-wagon-gray',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 240000, oemIntervalMonths: 120, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Brake Fluid', oemIntervalKm: 45000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 240000, oemIntervalMonths: 120, type: 'Chassis' },
    ],
  },
  {
    id: 'honda-accord-cl9',
    make: 'Honda',
    model: 'Accord Euro',
    variant: 'CL9 (K24A)',
    years: '2003-2007',
    imageId: 'placeholder-sedan-black',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Brake Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 200000, oemIntervalMonths: 120, type: 'Chassis' },
    ],
  },
];
