import type { Vehicle } from './types';

export const VEHICLE_DATABASE: Vehicle[] = [
  {
    id: 'ford-falcon-fg-turbo',
    make: 'Ford',
    model: 'Falcon',
    variant: 'FG Turbo',
    years: '2008-2014',
    imageId: 'ford-falcon-fg-turbo',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis' },
      { name: 'Differential Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 150000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
  },
  {
    id: 'toyota-86',
    make: 'Toyota',
    model: '86',
    variant: 'GT / GTS',
    years: '2012-2021',
    imageId: 'toyota-86',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 9, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 105000, oemIntervalMonths: 84, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Transmission Fluid', oemIntervalKm: 75000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Differential Fluid', oemIntervalKm: 75000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 160000, oemIntervalMonths: 96, type: 'Chassis' },
    ],
  },
    {
    id: 'sv6-commodore',
    make: 'Holden',
    model: 'Commodore',
    variant: 'SV6 (VE/VF)',
    years: '2006-2017',
    imageId: 'sv6-commodore',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 120000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Transmission Fluid', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis' },
      { name: 'Differential Fluid', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 240000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
  },
];
