
import type { Vehicle } from './types';
import { FITMENT_DATA } from './fitment-data';

export const VEHICLE_DATABASE: Vehicle[] = [
  // Existing Cars
  {
    id: 'ford-falcon-fg-turbo',
    make: 'Ford',
    model: 'Falcon',
    variant: 'FG/FG-X Turbo (Barra)',
    years: '2008-2016',
    imageId: 'ford-falcon-fg-turbo',
    specificVariants: ['XR6 Turbo', 'G6E Turbo'],
    modGuideId: 'barra-turbo',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Automatic Transmission Fluid (ZF 6HP)', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid (TR-6060)', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 120000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['ford-falcon-fg-turbo'],
  },
  {
    id: 'toyota-86',
    make: 'Toyota',
    model: '86 / GR86',
    variant: 'GT / GTS / ZN6 / ZN8',
    years: '2012-Present',
    imageId: 'toyota-86',
    specificVariants: ['GT', 'GTS', 'GR86'],
    modGuideId: 'zn6-zn8',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant (Super Long Life)', oemIntervalKm: 150000, oemIntervalMonths: 96, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['toyota-86'],
  },
  {
    id: 'sv6-commodore',
    make: 'Holden',
    model: 'Commodore',
    variant: 'SV6 (VE/VF - V6)',
    years: '2006-2017',
    imageId: 'sv6-commodore',
    specificVariants: ['SV6', 'Calais', 'Omega'],
    modGuideId: 'alloytec-v6',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 9, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 100000, oemIntervalMonths: 84, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 120000, oemIntervalMonths: 100, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 120000, oemIntervalMonths: 100, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 150000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['sv6-commodore'],
  },
  // Nissan Skylines
  {
    id: 'nissan-skyline-r32-gtst',
    make: 'Nissan',
    model: 'Skyline',
    variant: 'R32 GTS-t Turbo (RB20DET)',
    years: '1989-1994',
    imageId: 'placeholder-coupe-gray',
    specificVariants: ['GTS-t Type M'],
    modGuideId: 'rb20det',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 5000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 20000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['nissan-skyline-r32-gtst'],
  },
  {
    id: 'nissan-skyline-r32-gtr',
    make: 'Nissan',
    model: 'Skyline GT-R',
    variant: 'R32 (RB26DETT)',
    years: '1989-1994',
    imageId: 'placeholder-coupe-dark',
    specificVariants: ['Standard', 'V-Spec', 'V-Spec II', 'N1'],
    modGuideId: 'rb26dett',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 5000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Platinum)', oemIntervalKm: 20000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis', transmission: 'Manual' },
      { name: 'Front Differential Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Rear Differential Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'ATTESA Transfer Case Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['nissan-skyline-r32-gtr'],
  },
   {
    id: 'nissan-skyline-r33-gts',
    make: 'Nissan',
    model: 'Skyline',
    variant: 'R33 GTS Non-Turbo (RB25DE)',
    years: '1993-1998',
    imageId: 'placeholder-coupe-blue',
    specificVariants: ['GTS', 'GTS Type G'],
    // No specific mod guide for NA RB25 yet
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs (Platinum)', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['nissan-skyline-r33-gtst'], // Fitment is similar to GTS-t
  },
  {
    id: 'nissan-skyline-r33-gtst',
    make: 'Nissan',
    model: 'Skyline',
    variant: 'R33 GTS25t Turbo (RB25DET)',
    years: '1993-1998',
    imageId: 'placeholder-coupe-blue',
    specificVariants: ['GTS25t Spec 1', 'GTS25t Spec 2'],
    modGuideId: 'rb25det',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 7500, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Platinum)', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['nissan-skyline-r33-gtst'],
  },
  {
    id: 'nissan-skyline-r34-gt',
    make: 'Nissan',
    model: 'Skyline',
    variant: 'R34 GT Non-Turbo (RB25DE NEO)',
    years: '1998-2002',
    imageId: 'placeholder-coupe-silver',
    specificVariants: ['GT', '25GT-V'],
    // No specific mod guide for NA RB25 yet
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Platinum)', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['nissan-skyline-r34-gtt'], // Fitment is similar to GTT
  },
  {
    id: 'nissan-skyline-r34-gtt',
    make: 'Nissan',
    model: 'Skyline',
    variant: 'R34 GTT Turbo (RB25DET NEO)',
    years: '1998-2002',
    imageId: 'placeholder-coupe-silver',
    specificVariants: ['GTT'],
    modGuideId: 'rb25det-neo',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Platinum)', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['nissan-skyline-r34-gtt'],
  },
  {
    id: 'nissan-skyline-r34-gtr',
    make: 'Nissan',
    model: 'Skyline GT-R',
    variant: 'R34 (RB26DETT)',
    years: '1999-2002',
    imageId: 'placeholder-coupe-blue-fast',
    specificVariants: ['Standard', 'V-Spec', 'V-Spec II', 'M-Spec', 'Nür'],
    modGuideId: 'rb26dett',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 7500, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid (Getrag)', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Front Differential Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Rear Differential Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'ATTESA Transfer Case Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['nissan-skyline-r34-gtr'],
  },
  // Ford Falcons
  {
    id: 'ford-falcon-au',
    make: 'Ford',
    model: 'Falcon',
    variant: 'AU I6 (Intech)',
    years: '1998-2002',
    imageId: 'placeholder-sedan-gold',
    specificVariants: ['Forte', 'Futura', 'XR6'],
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 45000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 120000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['ford-falcon-au'],
  },
  {
    id: 'ford-falcon-ba-bf',
    make: 'Ford',
    model: 'Falcon',
    variant: 'BA/BF I6 (Barra)',
    years: '2002-2008',
    imageId: 'placeholder-sedan-silver',
    specificVariants: ['XT', 'Futura', 'Fairmont', 'XR6'],
    modGuideId: 'barra-na',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Automatic Transmission Fluid (4-speed)', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 45000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['ford-falcon-ba-bf'],
  },
  // VW Golf R
  {
    id: 'vw-golf-r-mk5',
    make: 'Volkswagen',
    model: 'Golf R32',
    variant: 'Mk5 (3.2 VR6)',
    years: '2005-2008',
    imageId: 'placeholder-hatch-blue',
    specificVariants: ['R32'],
    modGuideId: 'vr6-3-2',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Haldex Fluid & Filter', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'DSG Transmission Fluid & Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Manual' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 120000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['vw-golf-r-mk5'],
  },
  {
    id: 'vw-golf-r-mk6',
    make: 'Volkswagen',
    model: 'Golf R',
    variant: 'Mk6 (EA113)',
    years: '2009-2013',
    imageId: 'placeholder-hatch-black',
    specificVariants: ['Golf R'],
    modGuideId: 'ea113',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt & Water Pump', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Cam Follower', oemIntervalKm: 20000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Haldex Fluid & Filter', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'DSG Transmission Fluid & Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Manual' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['vw-golf-r-mk6'],
  },
  {
    id: 'vw-golf-r-mk7',
    make: 'Volkswagen',
    model: 'Golf R',
    variant: 'Mk7/7.5 (EA888 Gen3)',
    years: '2013-2020',
    imageId: 'placeholder-hatch-lapiz',
    specificVariants: ['R', 'R Performance Pack'],
    modGuideId: 'ea888-gen3',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Haldex Fluid', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'DSG Transmission Fluid & Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 120000, oemIntervalMonths: 96, type: 'Chassis', transmission: 'Manual' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['vw-golf-r-mk7'],
  },
  {
    id: 'vw-golf-r-mk8',
    make: 'Volkswagen',
    model: 'Golf R',
    variant: 'Mk8 (EA888 Gen4)',
    years: '2021-Present',
    imageId: 'placeholder-hatch-white-modern',
    specificVariants: ['R', 'R Performance'],
    modGuideId: 'ea888-gen3', // Gen4 is very similar to Gen3 for basic stages
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Haldex Fluid', oemIntervalKm: 40000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'DSG Transmission Fluid & Filter', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Brake Fluid', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['vw-golf-r-mk8'],
  },
  // Other Cars
  {
    id: 'mercedes-ml500',
    make: 'Mercedes-Benz',
    model: 'ML 500',
    variant: 'W164 (M273 V8)',
    years: '2007-2011',
    imageId: 'placeholder-suv-black',
    specificVariants: ['ML 500'],
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 15000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Automatic Transmission Fluid (7G-Tronic)', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Transfer Case Fluid', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis' },
      { name: 'Front Differential Fluid', oemIntervalKm: 120000, oemIntervalMonths: 72, type: 'Chassis' },
      { name: 'Rear Differential Fluid', oemIntervalKm: 120000, oemIntervalMonths: 72, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['mercedes-ml500'],
  },
  {
    id: 'ford-mondeo-mc',
    make: 'Ford',
    model: 'Mondeo',
    variant: 'MC EcoBoost',
    years: '2015-2022',
    imageId: 'placeholder-wagon-gray',
    specificVariants: ['Ambiente', 'Trend', 'Titanium'],
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 90000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Brake Fluid', oemIntervalKm: 45000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['ford-mondeo-mc'],
  },
  {
    id: 'honda-accord-cl9',
    make: 'Honda',
    model: 'Accord Euro',
    variant: 'CL9 (K24A)',
    years: '2003-2007',
    imageId: 'placeholder-sedan-black',
    specificVariants: ['Standard', 'Luxury'],
    modGuideId: 'k24a',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Brake Fluid', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['honda-accord-cl9'],
  },
  // START OF NEW CARS
  // Subaru
  {
    id: 'subaru-wrx-sti-gc8',
    make: 'Subaru',
    model: 'Impreza WRX/STI',
    variant: 'GC8 (EJ20)',
    years: '1992-2000',
    imageId: 'placeholder-coupe-blue',
    specificVariants: ['WRX', 'STI', 'Type R', '22B'],
    modGuideId: 'ej20',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 7500, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 30000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 50000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['subaru-wrx-sti-gc8'],
  },
  {
    id: 'subaru-wrx-sti-gd-5x100',
    make: 'Subaru',
    model: 'Impreza WRX/STI (5x100)',
    variant: 'GD "Bug/Blob/Hawk" (EJ20/EJ25)',
    years: '2001-2004',
    imageId: 'placeholder-coupe-blue-fast',
    specificVariants: ['WRX', 'STI'],
    modGuideId: 'ej20', // Covers early GDs
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 105000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['subaru-wrx-sti-gd-5x100'],
  },
    {
    id: 'subaru-wrx-sti-gd-5x114',
    make: 'Subaru',
    model: 'Impreza STI (5x114.3)',
    variant: 'GD "Hawkeye" (EJ25)',
    years: '2005-2007',
    imageId: 'placeholder-coupe-blue-fast',
    specificVariants: ['STI', 'S203', 'S204'],
    modGuideId: 'ej25',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 105000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['subaru-wrx-sti-gd-5x114'],
  },
  {
    id: 'subaru-wrx-sti-va',
    make: 'Subaru',
    model: 'WRX/STI',
    variant: 'VA (FA20/EJ25)',
    years: '2015-2021',
    imageId: 'placeholder-sedan-silver',
    specificVariants: ['WRX', 'WRX Premium', 'STI', 'STI Premium', 'S209'],
    modGuideId: 'ej25', // STI uses EJ25
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 96000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid (CVT)', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 60000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 120000, oemIntervalMonths: 72, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['subaru-wrx-sti-va'],
  },
  // Mitsubishi
  {
    id: 'mitsubishi-evo-8-9',
    make: 'Mitsubishi',
    model: 'Lancer Evolution',
    variant: 'VIII/IX (4G63)',
    years: '2003-2007',
    imageId: 'placeholder-sedan-silver',
    specificVariants: ['VIII GSR', 'VIII MR', 'IX GSR', 'IX MR'],
    modGuideId: '4g63',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 7500, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Timing Belt', oemIntervalKm: 96000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis', transmission: 'Manual' },
      { name: 'Transfer Case Fluid', oemIntervalKm: 24000, oemIntervalMonths: 12, type: 'Chassis' },
      { name: 'Rear Differential Fluid', oemIntervalKm: 24000, oemIntervalMonths: 12, type: 'Chassis' },
      { name: 'AYC/ACD Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['mitsubishi-evo-8-9'],
  },
  {
    id: 'mitsubishi-evo-10',
    make: 'Mitsubishi',
    model: 'Lancer Evolution',
    variant: 'X (4B11)',
    years: '2008-2016',
    imageId: 'placeholder-sedan-black',
    specificVariants: ['GSR', 'MR', 'Final Edition'],
    modGuideId: '4b11',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 7500, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 96000, oemIntervalMonths: 60, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Timing Chain', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 96000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'SST Transmission Fluid & Filter', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Transfer Case Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Rear Differential Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'AYC/ACD Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['mitsubishi-evo-10'],
  },
  // Mazda
  {
    id: 'mazda-mx5-nd',
    make: 'Mazda',
    model: 'MX-5',
    variant: 'ND (SkyActiv-G)',
    years: '2015-Present',
    imageId: 'toyota-86', // Visually similar
    specificVariants: ['Roadster', 'RF', 'Club', 'Grand Touring'],
    modGuideId: 'zn6-zn8', // Similar class of car
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 120000, oemIntervalMonths: 96, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['mazda-mx5-nd'],
  },
  {
    id: 'mazda-rx7-fd',
    make: 'Mazda',
    model: 'RX-7',
    variant: 'FD (13B-REW)',
    years: '1992-2002',
    imageId: 'placeholder-coupe-dark',
    specificVariants: ['Type R', 'Type RS', 'Type RZ', 'Spirit R'],
    modGuideId: '13b-rew',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 5000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Rotary)', oemIntervalKm: 20000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 20000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['mazda-rx7-fd'],
  },
  // Honda
  {
    id: 'honda-s2000',
    make: 'Honda',
    model: 'S2000',
    variant: 'AP1/AP2 (F20C/F22C)',
    years: '1999-2009',
    imageId: 'placeholder-coupe-silver',
    specificVariants: ['AP1', 'AP2', 'CR'],
    modGuideId: 'f20c-f22c',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 25000, oemIntervalMonths: 12, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['honda-s2000'],
  },
  {
    id: 'honda-civic-type-r-fk8',
    make: 'Honda',
    model: 'Civic Type R',
    variant: 'FK8 (K20C1)',
    years: '2017-2021',
    imageId: 'placeholder-hatch-white-modern',
    specificVariants: ['Type R', 'Type R GT'],
    modGuideId: 'k20c1',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Brake Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['honda-civic-type-r-fk8'],
  },
  // BMW
  {
    id: 'bmw-m3-e46',
    make: 'BMW',
    model: 'M3',
    variant: 'E46 (S54)',
    years: '2000-2006',
    imageId: 'placeholder-coupe-gray',
    specificVariants: ['M3 Coupe', 'M3 Convertible', 'CSL'],
    modGuideId: 's54',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Valve Adjustment', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Fuel Filter', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'SMG Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['bmw-m3-e46'],
  },
  {
    id: 'bmw-m2-f87',
    make: 'BMW',
    model: 'M2',
    variant: 'F87 (N55/S55)',
    years: '2016-2021',
    imageId: 'placeholder-coupe-blue',
    specificVariants: ['M2', 'M2 Competition', 'M2 CS'],
    modGuideId: 'n55-s55',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 60000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 45000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis', transmission: 'Manual' },
      { name: 'DCT Transmission Fluid & Filter', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 45000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['bmw-m2-f87'],
  },
  // Ford (US)
  {
    id: 'ford-mustang-s550',
    make: 'Ford',
    model: 'Mustang GT',
    variant: 'S550 (5.0 Coyote)',
    years: '2015-2023',
    imageId: 'placeholder-coupe-dark',
    specificVariants: ['GT', 'GT Premium', 'Bullitt', 'Mach 1'],
    modGuideId: 'coyote-s550',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 120000, oemIntervalMonths: 96, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 150000, oemIntervalMonths: 96, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 150000, oemIntervalMonths: 96, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 160000, oemIntervalMonths: 72, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['ford-mustang-s550'],
  },
  // Nissan Z
  {
    id: 'nissan-350z',
    make: 'Nissan',
    model: '350Z',
    variant: 'Z33 (VQ35DE/HR)',
    years: '2003-2008',
    imageId: 'placeholder-coupe-silver',
    specificVariants: ['Track', 'Touring', 'Grand Touring', 'Nismo'],
    modGuideId: 'vq35',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['nissan-350z'],
  },
  // New Additions
  {
    id: 'honda-accord-2000',
    make: 'Honda',
    model: 'Accord',
    variant: '6th Gen (F-series)',
    years: '1998-2002',
    imageId: 'placeholder-sedan-white',
    specificVariants: ['DX', 'LX', 'EX', 'V6'],
    modGuideId: 'k24a', // Similar principles apply
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 72000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['honda-accord-2000'],
  },
  {
    id: 'honda-accord-2008',
    make: 'Honda',
    model: 'Accord',
    variant: '8th Gen (K24/J35)',
    years: '2008-2012',
    imageId: 'placeholder-sedan-gray',
    specificVariants: ['LX', 'EX', 'EX-L V6'],
    modGuideId: 'k24a',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs (Iridium)', oemIntervalKm: 160000, oemIntervalMonths: 96, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 96000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 160000, oemIntervalMonths: 120, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['honda-accord-2008'],
  },
    {
    id: 'honda-accord-2018',
    make: 'Honda',
    model: 'Accord',
    variant: '10th Gen (1.5T/2.0T)',
    years: '2018-2022',
    imageId: 'placeholder-sedan-black',
    specificVariants: ['Sport 1.5T', 'Sport 2.0T', 'Touring 2.0T'],
    modGuideId: 'k20c1', // 2.0T is related
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Coolant', oemIntervalKm: 160000, oemIntervalMonths: 120, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['honda-accord-2018'],
  },
  {
    id: 'nissan-skyline-v35',
    make: 'Nissan',
    model: 'Skyline / Infiniti G35',
    variant: 'V35 (VQ35DE)',
    years: '2001-2007',
    imageId: 'placeholder-coupe-silver',
    specificVariants: ['350GT', 'G35 Coupe', 'G35 Sedan'],
    modGuideId: 'vq35',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 100000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 50000, oemIntervalMonths: 36, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 40000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['nissan-skyline-v35'],
  },
  {
    id: 'infiniti-q50-q60',
    make: 'Infiniti',
    model: 'Q50 / Q60',
    variant: 'V37 (VR30DDTT)',
    years: '2016-Present',
    imageId: 'placeholder-coupe-red-90s',
    specificVariants: ['3.0t Luxe', 'Red Sport 400'],
    modGuideId: 'vr30ddtt',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 10000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 96000, oemIntervalMonths: 48, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 120000, oemIntervalMonths: 96, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['infiniti-q50-q60'],
  },
  {
    id: 'mustang-foxbody',
    make: 'Ford',
    model: 'Mustang',
    variant: 'Fox Body (5.0L)',
    years: '1987-1993',
    imageId: 'placeholder-coupe-white-80s',
    specificVariants: ['LX 5.0', 'GT'],
    modGuideId: 'foxbody-5.0',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 5000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 80000, oemIntervalMonths: 48, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['mustang-foxbody'],
  },
  {
    id: 'mustang-sn95',
    make: 'Ford',
    model: 'Mustang',
    variant: 'SN95 / New Edge (4.6L/5.0L)',
    years: '1994-2004',
    imageId: 'placeholder-coupe-red-90s',
    specificVariants: ['GT', 'Cobra', 'Bullitt', 'Mach 1'],
    modGuideId: 'foxbody-5.0', // Similar principles
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 8000, oemIntervalMonths: 6, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 120000, oemIntervalMonths: 72, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 100000, oemIntervalMonths: 60, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 24, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['mustang-sn95'],
  },
  {
    id: 'mustang-s197',
    make: 'Ford',
    model: 'Mustang',
    variant: 'S197 (4.6L/5.0L)',
    years: '2005-2014',
    imageId: 'placeholder-coupe-blue-muscle',
    specificVariants: ['GT', 'Boss 302', 'Shelby GT500'],
    modGuideId: 'coyote-s550', // Similar principles
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 120000, oemIntervalMonths: 96, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 150000, oemIntervalMonths: 96, type: 'Chassis', transmission: 'Manual' },
      { name: 'Differential Fluid', oemIntervalKm: 150000, oemIntervalMonths: 96, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['mustang-s197'],
  },
   {
    id: 'mustang-s650',
    make: 'Ford',
    model: 'Mustang',
    variant: 'S650 (5.0 Coyote)',
    years: '2024-Present',
    imageId: 'placeholder-coupe-black-muscle',
    specificVariants: ['GT', 'Dark Horse'],
    modGuideId: 'coyote-s550',
    serviceItems: [
      { name: 'Engine Oil & Filter', oemIntervalKm: 12000, oemIntervalMonths: 12, type: 'Engine' },
      { name: 'Spark Plugs', oemIntervalKm: 120000, oemIntervalMonths: 96, type: 'Engine' },
      { name: 'Engine Air Filter', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Engine' },
      { name: 'Manual Transmission Fluid', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis', transmission: 'Manual' },
      { name: 'Automatic Transmission Fluid', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis', transmission: 'Automatic' },
      { name: 'Differential Fluid', oemIntervalKm: 150000, oemIntervalMonths: 120, type: 'Chassis' },
      { name: 'Brake Fluid', oemIntervalKm: 48000, oemIntervalMonths: 36, type: 'Chassis' },
    ],
    fitment: FITMENT_DATA['mustang-s650'],
  },
];
